### DISCUSSION TITLE
FOUC problem and FIX - Issue with gsap animation when page load.

### DISCUSSION THREAD

**Discussion by vijaykumarim** [sinanisler/snn-brx-child-theme#81] [Ideas]
When I load the page the content is loading twice and then animations are executing. It is causing this flicker content issue. What is causing this issue and how can I resolve it?

here is a screen capture video: https://jam.dev/c/4012ed55-4120-4321-a437-d595e0f1884a

Thank you

**Comment by Foamable** [comment]
Follow :)

**Comment by vijaykumarim** [comment]
fixed the issue with good old Gemini. 
 

 **Use `visibility: hidden;` in CSS and `autoAlpha` in GSAP:**
    This is the most common and recommended approach for GSAP.

    * **In your CSS (for the elements you want to animate):**
        Add `visibility: hidden;` to the CSS of the elements that will be animated. This ensures they are completely hidden from the start, preventing the initial "flash."
        ```css
        .my-animated-element {
            visibility: hidden;
            /* Add any other initial styles here, e.g., opacity: 0; */
        }
        ```
 

**Hope this helps. But I think it should automatically taken care instead of adding visibility hidden. Hope @sinanisler  can address the issue.** 

Thank you
